CREATE TABLE USERS (
    ID INT NOT NULL PRIMARY KEY CLUSTERED,
    EMAIL varchar(255) NOT NULL,
    USER_NAME varchar(255),
    ACTIVE INT NOT NULL DEFAULT(0)
);

CREATE SEQUENCE USERS_SEQ
    as int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    NO CACHE;