CREATE TABLE SUBSCRIPTION_PLAN (
    ID_SUBSCRIPTION_PLAN INT NOT NULL PRIMARY KEY CLUSTERED,
    PRICE DECIMAL NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION NVARCHAR(MAX)
);

CREATE SEQUENCE SUBSCRIPTION_PLAN_SEQ
    as int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    NO CACHE;