CREATE TABLE PLANS (
    ID INT NOT NULL PRIMARY KEY CLUSTERED,
    PRICE DECIMAL(10,2) NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION NVARCHAR(MAX)
);

CREATE SEQUENCE PLANS_SEQ
    as int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    NO CACHE;