CREATE TABLE SUBSCRIPTIONS (
    ID INT NOT NULL PRIMARY KEY CLUSTERED,
    ID_USER INT NOT NULL,
    ID_PLAN INT NOT NULL,
    EXPIRATION_DATE DATETIME NULL
);

CREATE SEQUENCE SUBSCRIPTION_PLAN_SEQ
    as int
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    NO CACHE;